---
- name: Add cluster admin role to admin user
  shell: "oc adm policy add-cluster-role-to-user cluster-admin {{rhsso_cluster_admin_username}}"
  register: policy_cmd
  failed_when: policy_cmd.rc != 0

- name: apply view roles to evals-admin user
  shell: "oc adm policy add-cluster-role-to-user view {{rhsso_evals_admin_username}}"
  register: policy_cmd
  failed_when: policy_cmd.rc != 0